[phases.build]
cmds = ["pip install -r backend/requirements.txt"]

[phases.setup]
nixPkgs = ["python39"]

[start]
cmd = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
